# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5891d01d3dc094aa32224f7fec8c05d53206237ed16e7c8c40b8e8692d6808b9c422b4ba41ff24240e0fe9fd1b03aa232952deaaaa2cc80496f9947f5c7f663

test:
  secret_key_base: 438d4f33d406ab530957e437abc797f0c749e4e2526fa0e0d0f6335c118b17100d3f136c8aa34c4b115db596e3110fa505f3a52e8a6adb9579cc192a6f344b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
